name: easypeasy_sdk
publish_to: "none"
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  image: ^3.2.2
  xml2json: ^5.3.5
  http: ^0.13.5
  dcli: ^1.36.0
  url_launcher: ^6.1.7
  easypeasy_entities:
    path: ..\easypeasy_entities

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
